# Generated by Django 6.0.4 on 2026-07-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bus_seats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('train', 'Train'), ('package', 'Package'), ('car', 'Car'), ('bus', 'Bus')], max_length=10),
        ),
    ]
