# Generated by Django 6.0.7 on 2026-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_bus_booking_booking_bus_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
    ]
