# Generated by Django 6.0.6 on 2026-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=4.5)),
                ('duration', models.CharField(max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Domestic', max_length=50)),
                ('itinerary', models.TextField(default='[]')),
                ('gallery', models.TextField(default='[]')),
            ],
        ),
    ]
