# Generated by Django 6.0.6 on 2026-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_discount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('discount_tag', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='flights', max_length=50)),
            ],
        ),
    ]
