# Generated by Django 6.0.6 on 2026-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(default='Automatic', max_length=50)),
                ('fuel_type', models.CharField(default='Petrol', max_length=50)),
                ('rental_type', models.CharField(default='Self Drive', max_length=50)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('features', models.TextField(default='[]')),
            ],
        ),
    ]
