# Generated by Django 5.2.14 on 2026-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_platform',
            field=models.CharField(default='Platform 2', max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_platform',
            field=models.CharField(default='Platform 1', max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='district_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='sub_district_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
