# Generated by Django 5.2.14 on 2026-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_train_arrival_platform_train_departure_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='arrival_platform',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure_platform',
        ),
        migrations.RemoveField(
            model_name='train',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='train',
            name='sub_district_name',
        ),
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
