# Generated by Django 6.0.4 on 2026-07-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
