# Generated by Django 6.0.7 on 2026-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
