# Generated by Django 5.0.6 on 2026-08-22 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cover_photo', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('budget_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=150)),
                ('country_name', models.CharField(max_length=150)),
                ('cost_index', models.CharField(default='$$', max_length=10)),
                ('popularity', models.CharField(default='High', max_length=100)),
                ('date', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Sightseeing', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('start_time', models.CharField(default='09:00 AM', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.tripstop')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
