# Generated by Django 5.0.6 on 2026-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripactivity',
            name='category',
            field=models.CharField(blank=True, default='Sightseeing', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripactivity',
            name='name',
            field=models.CharField(default='Activity', max_length=200),
        ),
        migrations.AlterField(
            model_name='tripactivity',
            name='start_time',
            field=models.CharField(blank=True, default='09:00 AM', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='city_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='cost_index',
            field=models.CharField(blank=True, default='$$', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='country_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='popularity',
            field=models.CharField(blank=True, default='High', max_length=100, null=True),
        ),
    ]
