# Generated by Django 6.0.6 on 2026-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('train_number', models.CharField(max_length=20)),
                ('source_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('train_type', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField(default=60)),
                ('available_seats', models.IntegerField(default=60)),
                ('booked_seats', models.TextField(default='[]')),
            ],
        ),
    ]
